# Generated by Django 3.0.2 on 2020-02-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
