# Generated by Django 3.0.3 on 2020-02-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('id_number', models.DateTimeField(auto_now=True)),
                ('messages_student', models.TextField()),
                ('address', models.CharField(default='Not Set', max_length=150)),
                ('is_studying', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'תלמיד',
                'verbose_name_plural': 'תלמידים',
            },
        ),
    ]
