# Generated by Django 3.0.3 on 2020-02-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200213_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('ז', 'זכר'), ('נ', 'נקבה')], max_length=1),
        ),
    ]
