# Generated by Django 3.0.3 on 2020-02-13 17:01

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200213_1840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foo',
            new_name='Gender',
        ),
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(default='ז', upload_to=students.models.user_directory_path),
            preserve_default=False,
        ),
    ]
