# Generated by Django 3.0.3 on 2020-02-13 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_studies', models.CharField(max_length=4)),
                ('id_school', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('names_school', models.CharField(max_length=30)),
                ('school_network', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(7)])),
                ('descrip_school_network', models.CharField(max_length=40)),
                ('school_typle', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2)])),
                ('descrip_school_typle', models.CharField(max_length=20)),
                ('reporting', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2)])),
                ('descrip_reporting', models.CharField(max_length=20)),
                ('sector', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1)])),
                ('descrip_sector', models.CharField(max_length=10)),
                ('legal_status', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1)])),
                ('descrip_legal_Status', models.CharField(max_length=20)),
                ('inspection_type', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1)])),
                ('descrip_inspection_type', models.CharField(max_length=20)),
                ('type_education', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2)])),
                ('descrip_type_education', models.CharField(max_length=5)),
                ('education_phase', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1)])),
                ('descrip_educationPhase', models.CharField(max_length=20)),
                ('id_city', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('city', models.CharField(max_length=20)),
                ('address_school', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
                ('fax', models.CharField(max_length=11)),
                ('facebook', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'מוסד לימוד',
                'verbose_name_plural': 'מוסדות לימוד',
            },
        ),
    ]
