# Generated by Django 3.0.2 on 2020-02-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='id_school',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='schools',
            name='name_school',
            field=models.CharField(default='dasd', max_length=200),
            preserve_default=False,
        ),
    ]
