# Generated by Django 3.0.3 on 2020-02-13 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_schools_reporting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='descrip_type_education',
        ),
        migrations.AlterField(
            model_name='schools',
            name='education_phase',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='schools',
            name='id_city',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='schools',
            name='id_school',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='schools',
            name='inspection_type',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='schools',
            name='legal_status',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='schools',
            name='reporting',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='schools',
            name='school_network',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AlterField(
            model_name='schools',
            name='school_typle',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='schools',
            name='sector',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='schools',
            name='type_education',
            field=models.CharField(max_length=5),
        ),
    ]
