# Generated by Django 3.0.3 on 2020-02-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.DateTimeField()),
                ('name_school', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'הנה"ח',
                'verbose_name_plural': 'הנה"ח',
            },
        ),
    ]
