# Generated by Django 3.0.3 on 2020-02-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'מערכת שעות ואירועים',
                'verbose_name_plural': 'מערכת שעות ואירועים',
            },
        ),
    ]
